### ISSUE TITLE
How to set min and max value of the slider.

### ISSUE THREAD

**Issue by saulojoab** [kALLEBALIK/react-slider-simple#2]
Love your slider, super simple and easy to use. May I ask how to set the min-max value of the slider? It seems like it's `min: 0 | max: 100` by default. Thank you!

**Comment by kALLEBALIK** [comment]
Hi! well my thought was that it doesn't need a min-max value because it works in percent.
So if you want the max value to be 50 you just output: Value / 2.  I hope i understood your question correctly. Hope this helped :)

**Comment by saulojoab** [comment]
Hi, thanks for the quick response. Is there any way to make with work with number intervals instead of percentage? 

In the image below, I clicked in the middle of the Scale Y slider. It changes the value correctly but it's so low that you don't really see any visual feedback on the slider. That's why I wanted to set a min-max value.

![image](https://user-images.githubusercontent.com/37988252/62721467-a4320600-b9e2-11e9-8c31-343763af2378.png)

Or maybe I'm just too dummy dumb to get how the slider actually works haha

**Comment by kALLEBALIK** [comment]
Keep the percent and your data separate and think of the percentage value as a value that controles where on the slider the thumb appears. 
```
import React from 'react';
import Slider from 'react-slider-simple';

class SliderComp extends React.Component {
  state  = {
    percent: 30,
    displayValue: 15,
  }

  onChange = (percent) => {
    const displayValue = percent / 100 * 500;
    this.setState({ percent, displayValue });

    console.log(this.state.percent);          // displays 0 - 100
    console.log(this.state.displayValue);  // displays 0 - 500
  }

  render() {
    const { percent } = this.state;
    return (
        <Slider
          value={percent /* Dictates where the thumb is on slider */}
          onChange={this.onChange}
        />
    );
  }
}
```
